version: '3.7' 

services:
  gateway:
    build: .
    working_dir: /opt/gateway
    volumes: 
      - "./bin/gateway:/opt/gateway/bin/gateway"
    environment:
      - "DB_NAME=gateway"
      - "DB_USER=user"
      - "DB_PASSWORD=pass"
      - "DB_ADDRESS=dev-db"
    ports:
      - 8080:8080
    entrypoint: /opt/gateway/bin/gateway

  dev-db:
    image: mariadb:10.5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'gateway'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    volumes:             
      - ./cfg/init:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306